### ISSUE TITLE
Two strains with different ploidy?

### ISSUE THREAD

**Issue by ricen90** [schatzlab/genomescope#108]
Hi, 
I sequenced several strains of the same fungus species. The size of most genomes is around 65Mb, but there were also smaller samples (around 43Mb) and slightly larger (>80Mb) samples. The reference genome of the same species is 53Mb, but according to the publication it's a diploid organism (63Mb with tandem repeats) and the haploid genome size is 42Mb. 
Is it possible that some strains are haploid and some diploid? For sample with genome size of 43Mb, most BUSCOs are single-copy, while 82Mb sample have many duplicated genes. 
The GenomeScope2 results look as follows:
Sample 7 (43Mb) with ploidy set to 1: 
http://genomescope.org/genomescope2.0/analysis.php?code=6DccaSlrhxxWz1sgtHBa
Sample 7 (43Mb) with ploidy set to 2:
http://genomescope.org/genomescope2.0/analysis.php?code=Nfo9zRv5T6tFU6mzbtgp
Sample 36 (82Mb) with ploidy set to 1:
http://genomescope.org/genomescope2.0/analysis.php?code=W6ZGM64f73Dm2P1imqoe 
Sample 36 (82Mb) with ploidy set to 2:
http://genomescope.org/genomescope2.0/analysis.php?code=uaZUZARSy7q9EuiVn0mi
Sample 5 (64Mb) with ploidy set to 1:
http://genomescope.org/genomescope2.0/analysis.php?code=paCDiO0JRQyZwYPZBsfo
Sample 5 (64Mb) with ploidy set to 2:
http://genomescope.org/genomescope2.0/analysis.php?code=PyRMQ85poK23mKbQEEwQ

**Comment by mschatz** [comment]
It is always tricky for peaks like these - it could either be extremely high or extremely low rates of heterozygosity in a diploid sample.

For sample 7, the ploid=2 fit looks pretty good to me, and shows a modest level of heterozygosity (0.463%)

For sample 36, the ploidy=2 fit looks a bit better to me, but this implies the heterozygosity rate is 4.16% (for context outcross Arabidopsis is about 1%). This high rate is a little suspicious to me although is possible. This could also explain why you have high rates of BUSCO duplicate genes if the two haplotypes are highly divergent.

For sample 5, ploidy=2 also looks better to me, and shows a 2.5% heterogosity rate. How do the BUSCO results look? I would expect high rates of duplicates although maybe a bit less than sample 36

Good luck!
Mike

**Comment by ricen90** [comment]
Hi Mike, 
Thank you for your reply. BUSCO results show exactly what you said:
- reference sample (53Mb): 99% Complete (97% Single-copy, 2% Duplicated), 1% Fragmented;
- sample 7 (43Mb): 99% C (99% S, 0% D);
- sample 5 (64Mb): 99% C (77% S, 22% D), 1% F;
- sample 36 (82Mb): 99% C (45% S, 54% D), 1% F.
The same pattern was observed when analyzing another BUSCO dataset. 
However, I'm still working to understand the variations among my samples. We know that this fungal family consists of diploid species, as confirmed by GenomeScope2, which estimated a ploidy of 2 for all my samples with a haplotype genome size of approximately 40Mb. Does this mean that the differences in additional genomic material (2Mb for sample 7, 20Mb for sample 5, and 41Mb for sample 36) suggest varying levels of repetitive sequences and, consequently, differences in genome complexity?
I really appreciate your help!
R

**Comment by mschatz** [comment]
We cant draw this conclusion yet. Notice your kmer histograms end abruptly at 10,000 so all of your plots are missing the most repetitive sequence. This plus you have varying levels of coverage means the genome size estimates are not that reliable to compare. To get started, you should rerun kmc (or jellyfish) allowing a much higher cutoff for kmer coverage. For these data I would recommend at least 100,000 (and possibly higher). This will help normalize the differences in coverage you have. But this this analysis gets tricky because there can be low levels of contamination (even phiX) that can throw things off.  This is usually (but not always) recognized by abnormal peaks in the very high coverage range. We will have to see how it looks

Good luck
Mike


Good luck!
Mike
