### ISSUE TITLE
How to produce vector graph (i.e. pdf), not bitmap image i.e. .png)?

### ISSUE THREAD

**Issue by sanvva** [schatzlab/genomescope#111]

**Comment by mschatz** [comment]
There isnt a way to do this now, but I agree it would be a useful feature!
Let me look into it

**Comment by sanvva** [comment]
That would be great!

**Comment by arslan9732** [comment]
Hi @sanvva,
You can achieve this by just changing line 329, and 339 of [genomescope.R](https://github.com/schatzlab/genomescope/blob/master/genomescope.R)

**Default lines**
```
png(paste(foldername, "/plot.png", sep=""),width=plot_size,height=plot_size, res=resolution) #line329
png(paste(foldername, "/plot.log.png", sep=""),width=plot_size,height=plot_size,res=resolution) #line339
```
I assume [svglite](https://www.tidyverse.org/blog/2021/02/svglite-2-0-0/) is installed in your R.
**Replaced lines**
```
svg(paste(foldername, "/plot.svg", sep=""),width=10, height=10) #line329
svg(paste(foldername, "/plot.log.svg", sep=""),width=10, height=10) #line339
```
But it is for [genomescope](https://github.com/schatzlab/genomescope/tree/master) not for [genomescope2](https://github.com/tbenavi1/genomescope2.0).

**Comment by sanvva** [comment]
> Hi @sanvva, You can achieve this by just changing line 329, and 339 of [genomescope.R](https://github.com/schatzlab/genomescope/blob/master/genomescope.R)
> 
> **Default lines**
> 
> ```
> png(paste(foldername, "/plot.png", sep=""),width=plot_size,height=plot_size, res=resolution) #line329
> png(paste(foldername, "/plot.log.png", sep=""),width=plot_size,height=plot_size,res=resolution) #line339
> ```
> 
> I assume [svglite](https://www.tidyverse.org/blog/2021/02/svglite-2-0-0/) is installed in your R. **Replaced lines**
> 
> ```
> svg(paste(foldername, "/plot.svg", sep=""),width=10, height=10) #line329
> svg(paste(foldername, "/plot.log.svg", sep=""),width=10, height=10) #line339
> ```
> 
> But it is for [genomescope](https://github.com/schatzlab/genomescope/tree/master) not for [genomescope2](https://github.com/tbenavi1/genomescope2.0).
> 
> For [genomescope2](https://github.com/tbenavi1/genomescope2.0) you have to change the script [report_results.R](https://github.com/tbenavi1/genomescope2.0/blob/master/R/report_results.R) before installing genomescope locally.
> 
> change the line 103: **Default** plot_size=2000
> 
> **Replaced** plot_size=7
> 
> and then change the `png()` function at **line 114, 128, 143, 156, 823** such as: replace `png()` with `svg()`, change the file extension from `.png` to `.svg`, and remove the `res=resolution` from the function. Now run the command:
> 
> ```
> Rscript install.R
> ```
> 
> Now it will generate all graphs in SVG format.

Thank you very much!
