### ISSUE TITLE
No file uploaded error message

### ISSUE THREAD

**Issue by jferbe1** [schatzlab/genomescope#115]
I received this error on the web service. I believe the server has just filled up again. Thanks in advance!

<img width="1216" alt="Screenshot 2023-11-29 at 10 54 10 AM" src="https://github.com/schatzlab/genomescope/assets/152424838/28715819-ecc5-4082-a484-691e6062b782">

**Comment by mschatz** [comment]
Thanks for letting me know. The server had filled, but I was able to clean
up some space so things are working again.

Good luck!

Mike

**Comment by jferbe1** [comment]
Great, thank you!

Best,
Jackson
