### ISSUE TITLE
Heterozygous tetraploid genome model fit

### ISSUE THREAD

**Issue by RNieuwenhuis** [schatzlab/genomescope#125]
Hi,

I have a hard time to get a somewhat decent fit for the genome I am currently analyzing. It is a heterozygous autotetraploid sample with quite a large genome, so the coverage is somewhat limited. I have tried providing the coverage manually using -l but had no success, as the first peak is never included in the model. I was wondering if you could please help out as I have never seen this before. Is there anything I can try to get a decent fit?

The histogram tsv file:
[K_mer_kmc_db_k_21.txt](https://github.com/schatzlab/genomescope/files/14761736/K_mer_kmc_db_k_21.txt)

Best regards,

**Comment by mschatz** [comment]
Ive tried several different settings, but I cant find a parameterization
that Im confident in. Im afraid it is too low of coverage for it to be
reliable. Sorry I cant be more helpful here

Mike

**Comment by RNieuwenhuis** [comment]
Hi Mike,

Thanks for trying. It's reassuring we got the same result due to the low coverage. 

Kind regards,


Ronald Nieuwenhuis
