### ISSUE TITLE
Strange results, request interpretation

### ISSUE THREAD

**Issue by YPGG1234** [schatzlab/genomescope#136]
Thank you so much for developing such great software! Recently, I’ve been using >90 Gb of HiFi data to perform a genome survey on a rodent species, using k-mer 256 and k-mer 21, but the results seem to differ significantly from my expectations (because there’s an online genome for the same species, which is about ~3.X Gb in size, consistent with the flow cytometry results C-value 3.7). Here’s my command line:

```
cat $fastq | /usr/bin/time -v jellyfish count -o spe_256.jf -m  256  -s 3G  -t 50 --disk /dev/stdin
jellyfish histo -t 50 spe_256.jf > spe_256.histo
genomescope2 -i spe_256.histo -o k256 -p 2 -k 256
```

The k-mer 21 analysis used a similar command.

Here’s the summary.txt for k-mer 256:

```
GenomeScope version 2.0
input file = spe_256.histo
output directory = kmer256
p = 2
k = 256

property                      min               max               
Homozygous (aa)               94.6341%          100%              
Heterozygous (ab)             0%                5.3659%           
Genome Haploid Length         423,532,323 bp    429,588,336 bp    
Genome Repeat Length          84,381,523 bp     85,588,080 bp     
Genome Unique Length          339,150,800 bp    344,000,257 bp    
Model Fit                     79.2296%          86.8827%          
Read Error Rate               0.377496%         0.377496%      
```

And here are the transformed_linear_plot.png
![image](https://github.com/user-attachments/assets/560656a5-52b3-4869-bf75-edd6b6edcfea) 
and transformed_log_plot.png 
![image](https://github.com/user-attachments/assets/efebe568-e9cb-4e34-8c77-876cf392eda5)

Here’s the summary.txt for k-mer 21:

```
GenomeScope version 2.0
input file = spe_21.histo
output directory = k21
p = 2
k = 21

property                      min               max               
Homozygous (aa)               95.1379%          95.924%           
Heterozygous (ab)             4.07599%          4.86215%          
Genome Haploid Length         54,290,519 bp     56,337,190 bp     
Genome Repeat Length          45,002,897 bp     46,699,439 bp     
Genome Unique Length          9,287,622 bp      9,637,751 bp      
Model Fit                     35.1265%          85.0695%          
Read Error Rate               7.13116%          7.13116%   
```

And here are the transformed_linear_plot.png
![image](https://github.com/user-attachments/assets/517edc6b-bbb0-42b3-9dbc-9355994b20e0) 
and transformed_log_plot.png 
![image](https://github.com/user-attachments/assets/e45324fd-eb93-48b9-a772-53e030dc472e)

Additionally, it is worth mentioning that the contigs assembled by ```hifiasm``` using the default parameters show the following graph after using ```purge_haplotigs hist```, which may indicate that the genome's heterozygosity is not as high as predicted by GenomeScope2 [here](https://bitbucket.org/mroachawri/purge_haplotigs/issues/114/single-peak-in-histogram)
![image](https://github.com/user-attachments/assets/b0c71199-63c7-4ac0-b747-721092c0a9cf)

Could you please help me understand why the results are like this, and how I can improve to obtain more accurate results? The k-mer 256 results should be more accurate, but it seems the observed results do not fit well with the full model.

Looking forward to your reply. I would greatly appreciate your help if you can offer it!

**Comment by mschatz** [comment]
I would not use k=256 as this will really complicate the analysis. But the
fit for k=21 is also really poor and does not show a clear peak. Are you
sure you are looking at the CCS reads- from the shape of the distribution
it looks like there are some lower quality reads present. Can you try
FastQC on the data to make sure the reads have a QV around 30.

Good luck

Mike

**Comment by YPGG1234** [comment]
Thank you for your prompt response! The CCS sequences we are using are of very high quality, as shown in the image below:
![image](https://github.com/user-attachments/assets/f6329999-1d3d-459a-96ab-8950f2f33354)

At one point, we suspected that contamination might be present, leading to evaluation issues, but from the assembled contigs, it seems that this problem has a minimal impact (the "undef" and "unmapped" contigs are most likely due to the absence of this species in the NT database and Swissprot database).
![image](https://github.com/user-attachments/assets/c3b38fb7-599d-40f3-8c08-9c8ca66e487a)  ![image](https://github.com/user-attachments/assets/32e3581c-fc29-46ab-8681-ba36656b8512)

**Comment by mschatz** [comment]
It seems like something went really wrong - perhaps jellyfish crashed
before processing all of the reads. Can you send spe_21.histo?

Thanks!
Mike

**Comment by YPGG1234** [comment]
Here is the spe_21.histo file.
[spe_21.histo.txt](https://github.com/user-attachments/files/16743734/spe_21.histo.txt)

**Comment by YPGG1234** [comment]
Sorry, mschatz, regarding the input file for k21, there were some issues at that time: I only used 20-30% of the ~90 Gb data for the survey. When I used all the data for the survey, the results looked much better:
![transformed_linear_plot](https://github.com/user-attachments/assets/c2ca76f0-8fe1-492d-8fb6-2ec7258a95aa)

However, the estimated genome size (~3.X Gb) still differs significantly. Additionally, the second peak is missing. Could this difference be due to inbreeding and low heterozygosity? Here is the new `spe_21.histo`. [spe_21.all.histo.txt](https://github.com/user-attachments/files/16745395/spe_21.all.histo.txt)

**Comment by mschatz** [comment]
Yes, you have to provide all of the data to genomescope to get a good
estimate. I noticed in your jellyfish command that you are not including
the "-C" flag to consider canonical kmers. Can you try again with that
flag? That flag is needed to merge together coverage from the forward and
reverse strands. And can you also try using a higher maximum kmer frequency
(-h). For a mammalian genome I would try setting it to one million:
"jellyfish histo -h 1000000"

Good luck!
Mike

**Comment by YPGG1234** [comment]
Thank you for your response! I tried the parameters you suggested, and the results seem much more normal. 

Here is the `summary.txt`:
```
GenomeScope version 2.0
input file = spe_21.histo
output directory = k21
p = 2
k = 21

property                      min               max               
Homozygous (aa)               99.1438%          99.1917%          
Heterozygous (ab)             0.808265%         0.856189%         
Genome Haploid Length         2,980,569,086 bp  2,986,393,468 bp  
Genome Repeat Length          1,004,873,034 bp  1,006,836,674 bp  
Genome Unique Length          1,975,696,052 bp  1,979,556,794 bp  
Model Fit                     66.9321%          96.528%           
Read Error Rate               0.0804272%        0.0804272%        
```

However, the `transformed_linear_plot.png` still looks strange:

![image](https://github.com/user-attachments/assets/b1fb9dc0-bd94-4916-a42a-97ad29c84151)

It still doesn't seem to have a clear bimodal distribution, and two peaks appear at <20x and >60x. What could be causing this? Why is the bimodal distribution still not appearing? Looking forward to your reply.   [spe_21_C1.histo.txt](https://github.com/user-attachments/files/16780608/spe_21_C1.histo.txt)

**Comment by mschatz** [comment]
Great! These values look much more reasonable here.

The plot looks pretty reasonable to me. The estimated heterozygosity rate
(0.832%) is higher than a typical human (~0.2%) but not that surprising for
a rodent. What are you concerned about?

Good luck!

Mike

**Comment by YPGG1234** [comment]
In fact, in my expectation, the results of the SURVEY should be consistent with the figure below. I'm sorry, but this probably stems from my lack of understanding of how genomescope2 works.
https://www.researchgate.net/figure/Visual-overview-of-genome-assembly-metrics-A-K-mer-spectra-output-generated-from-PacBio_fig2_371697348

**Comment by mschatz** [comment]
I think I understand. In the example you linked, there is a high rate of
heterozygosity (1.5%) so there are two well defined peaks. Your sample has
a lower rate of heterozygosity so the first peak is less well defined,
although is still clearly visible. This is entirely expected - the relative
heights of the two peaks is proportional to the rate of heterozygosity. You
also have relatively low amounts of coverage for this type of analysis -
with high coverage the peaks will be better separated but here your peaks
are overlapping. But GenomeScope uses a statistical method called a mixture
model to figure this out.

For context, here is supplemental figure 1 from the GenomeScope paper
showing how the rate of heterozygosity impacts the relative heights of the
peaks (this is also with 100x coverage so the peaks are well separated)

[image: image.png]

Hope this helps!

Mike

**Comment by YPGG1234** [comment]
I think I understand and thank you very much for your patience!
