### ISSUE TITLE
Can we manually adjust the coverage judged as error?

### ISSUE THREAD

**Issue by wu116** [schatzlab/genomescope#138]
Hello! THANK for this perfect software!

I am facing a strange problem that genomescope may identified the heterozygous peak as an error.

I am working on a Poaceae species, which was consider as an allotetraploid before. And this is the transformed linear plot:
![transformed_linear_plot](https://github.com/user-attachments/assets/b7552dff-7d1e-47d4-9721-e499850992a3)

The first peak in the picture is ~8x, while the second/main peak is ~30x. It doesn't seem to meet the requirement of heterozygous peak = half of the main peak. But if we ignore the first peak, there was only one peak left, which might supposed this species as an diploid.

When I run genomescope with `p=2`, the result is liked that below. The DNA 1C value of my species from [C-values database](https://cvalues.science.kew.org/) was 3.5 pg.
![transformed_linear_plot](https://github.com/user-attachments/assets/e3739049-5419-4989-a1cb-79553f721db7)

The estimated genome size was closed to the 1C value, but I have no idea why there was a peak in error coverage. I'm not sure if it's diploid or tetraploid. Can we manually adjust the error coverage to normal coverage?

**Comment by mschatz** [comment]
Thanks for your interest! I agree this is a poor fit. There is a parameter
called "Average k-mer coverage for polyploid genome" that can be used as a
hint for examples like this. If you set it to 8 that should help resolve
things, but these higher ploidy genomes are always tricky to set up. If you
share the histogram file I can also try making some adjustments

Good luck!
Mike

**Comment by wu116** [comment]
Thanks for your kindly help!!!
I still worked on this question these day, since the main peak was located on ~30x, we sequenced again and gained ~50 Gb NGS data. With ~110 Gb NGS data we had, there were totally ~160 Gb NGS data now.
I tried to plot again with command line, the command is 
`genomescope.R -i km21.tsv -o km21_p4 -k 21 -p 4 --typical_error 2 --start_shift 1`
The transformed linear plot is
![transformed_linear_plot](https://github.com/user-attachments/assets/c752bcfb-76e5-48df-85c9-dd254d180e8f)

But in this plot, the main peak located in ~49x, the first peak loacted in ~11x as 1/5 main peak. This is too strange, because I think the first peak should also increase by ~20x to reach ~28x.

I tried the "Average k-mer coverage for polyploid genome" parameter (`8`) in the online web. The model fit the first peak well, but the genome size became `Inf`. 
Here is the result. http://genomescope.org/genomescope2.0/analysis.php?code=XQXQ07CWklappTJZMlsz

I also tried to set the `--kcov` as `8` with command line: 
`genomescope.R -i km21.tsv -o km21_p4 -k 21 -p 4 --typical_error 2 --start_shift 1 --kcov 8`
The result is like this:
![transformed_linear_plot](https://github.com/user-attachments/assets/45c13932-c26f-4e63-96d2-6dff19eb77a5)

The histogram files were generated by 
`jellyfish count -C -m 21 -s 20000M -o NGS_km21 -t 56 <(zcat clean_all_1.fq.gz) <(zcat clean_all_2.fq.gz)`
`jellyfish histo -t 56 -h 1000000 NGS_km21 > NGS_km21.tsv`
Here are three types of histogram files from kmer 17, 19, 21:
[NGS_km17.txt](https://github.com/user-attachments/files/16871705/NGS_km17.txt)
[NGS_km19.txt](https://github.com/user-attachments/files/16871702/NGS_km19.txt)
[NGS_km21.txt](https://github.com/user-attachments/files/16871704/NGS_km21.txt)

Could you please to help me figure out where the problem lies? Sincerely thanks again!!

**Comment by mschatz** [comment]
I tried adjusting the parameters but I never got a very satisfying result.
Ultimately the problem is that you have too low of coverage to resolve the
peaks, especially between the error kmers and 1st heterozygous peak (see
the very basic barplot showing a total lack of resolution on the low end).

I noticed that your file name is "clean" - does this mean you trimmed or
filtered the reads? Can you try again with the raw reads? Otherwise
unfortunately you will need to generate higher coverage.

Good luck
Mike

**Comment by wu116** [comment]
Yes, i have trimmed and filtered the reads. I tried to use the raw reads but got same result. 

I will think abot generate higher coverage data.

Thank!
