### ISSUE TITLE
How to fit model better?

### ISSUE THREAD

**Issue by gunjanpandey** [schatzlab/genomescope#139]
Could you please help me understand this results in detail?
This is from hifi data for a diploid plant, which was estimated (could be off) for around 4.2G. 

I want to understand, 
1. If the code the correct for a diploid or I need to modify some values (such as coverage or cutoff) for better model fitting?
2. What to make of the 100X model peak in the transformed liner plot. Is this is a model error? 
3. Is the coverage threshold correct or should it be around 1e+8 in transformed log plot?
4. I get the similar estimates for 19-31 kmers.

If better model fitting is possible, lease provide additional flags in my code below. I am new to genomescope2 and struggling with it. 

The run code and results are below.
```
        meryl count k=19 output k19.meryl ${HiFi}
        meryl histogram k19.meryl/ > k19_meryl.hist
        Rscript ${genomescope2} -i k19_meryl.hist -k 19 -o k19_genomescpe
        

**SUMMARY**        
GenomeScope version 2.0
input file = k19_meryl.hist
output directory = k19_genomescpe
p = 2
k = 19

property                      min               max               
Homozygous (aa)               97.8179%          97.9608%          
Heterozygous (ab)             2.03921%          2.1821%           
Genome Haploid Length         5,245,809,148 bp  5,308,629,526 bp  
Genome Repeat Length          4,725,949,621 bp  4,782,544,501 bp  
Genome Unique Length          519,859,527 bp    526,085,025 bp    
Model Fit                     13.268%           94.1095%          
Read Error Rate               0.0770237%        0.0770237%   

**MODEL**
Formula: y_transform ~ x^transform_exp * length * predict2_0(r1, k, d, kmercov, bias, x)

Parameters:
         Estimate Std. Error t value Pr(>|t|)    
d       2.114e-01  4.481e-03   47.19   <2e-16 ***
r1      2.111e-02  3.572e-04   59.09   <2e-16 ***
kmercov 2.508e+01  7.464e-02  336.02   <2e-16 ***
bias    6.788e-01  3.456e-02   19.64   <2e-16 ***
length  6.632e+08  5.119e+06  129.55   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 28650000 on 1995 degrees of freedom

Number of iterations to convergence: 7 
Achieved convergence tolerance: 1.49e-08
    
```

**Liner Plot**
<img width="529" alt="image" src="https://github.com/user-attachments/assets/1bec491b-6481-4c8b-ac62-fb1368d5e197">

**Transformed liner plot**
<img width="529" alt="image" src="https://github.com/user-attachments/assets/2d95690a-a3f5-45f9-ac91-fd2be049da12">

**Log plot**
<img width="529" alt="image" src="https://github.com/user-attachments/assets/4cbdd88a-e423-4bfc-9afc-a3e391e9daf7">

**Transformed log plot**
<img width="529" alt="image" src="https://github.com/user-attachments/assets/3208f553-846c-4691-ae53-4df3962f97c5">

**Comment by mschatz** [comment]
The fit here is pretty good, except the model (in black) is a bit below the
observed counts (in blue) for the heterozygous peak at 25x. This suggests
that GenomeScope has (modestly) underestimated the heterozygosity but I
expect the haploid genome length to still be around 5.3Gb. How did you get
the estimate for 4.2Gb? Have you tried running an assembler? For this
dataset I would recommend hifiasm. Note this has a high rate of
heterozygosity so the two haplotypes should assemble separately so will
need to look carefully at the primary assembly vs the individual haplotypes

Good luck!
Mike

**Comment by gunjanpandey** [comment]
Thanks for your prompt reply, Mike. I highly appreciate it. 
As you expect hifiasm does give an assembly of 5.3G.
