### ISSUE TITLE
Triploid genome

### ISSUE THREAD

**Issue by gunjanpandey** [schatzlab/genomescope#140]
This is not an issue but requesting help.
Could you please help understand the genome situation in regard to the genomescope plot?

This is supposed to be a triploid lizard of around 2.5G. 
With hifi and HiC data, hifiasm is generating three haplotypes as below.

<img width="992" alt="image" src="https://github.com/user-attachments/assets/f6809c25-377c-4c8e-b124-ad84805727c7">

<img width="623" alt="image" src="https://github.com/user-attachments/assets/0610c995-1ca7-4868-a1ba-581b2f0b0850">
<img width="684" alt="image" src="https://github.com/user-attachments/assets/4a5a49be-6037-43f4-be2c-224d5586c7b0">
<img width="684" alt="image" src="https://github.com/user-attachments/assets/9364667d-e2ec-48e3-ab28-37c2b96b5f2b">
<img width="684" alt="image" src="https://github.com/user-attachments/assets/05fd61e3-27f5-4cc4-9597-735d69cbb0b7">

I appreciate your help.

**Comment by mschatz** [comment]
From the shape of the kmer profile (in blue, without any modeling) I
would have guessed this to be a fairly heterozygous diploid as there are
not three well defined peaks. If you truly have a triploid sample, from the
overall shape, that would imply you have ~9x of each haplotype and these
three haplotypes are quite different from each other, although there are
some sequences that are shared between all three and some that are shared
between two but not all three. Have you tried SmudgePlot - that would help
visualize and interpret if there are 3 separate haplotypes. And when you
align your haplotypes to each other, do you see significant differences
between them? I would try rerunning as a diploid sample just to make sure
hifiasm is correctly separating.

Good luck!
Mike

**Comment by gunjanpandey** [comment]
Thanks Mike, 

This is a diploid lizard turning triploid so it would have a diploid pair + one extra set of chromosomes, we believe. 
I am yet to do the alignment. 

Closing this thread with thank you.
