### ISSUE TITLE
Failed to converge

### ISSUE THREAD

**Issue by jdmontenegro** [schatzlab/genomescope#19]
Hello everyone,
This tool looks quite useful since I was about to start writing some R code with the same purpose.
To get familiar with the program I simulated illumina data from a small plant diploid genome (genome size 13Mbp) and produced histograms for 17, 19, 21, 23 and 25 mers with kmc3 and jellyfish. The read simulation uses Illumina error profile to generate the reads and produces around 40X coverage of the haploid genome.
All kmer sizes histograms fail to converge even though I can clearly see two peaks in my data (see data below).
![plot](https://user-images.githubusercontent.com/9381306/54560689-ebb2e980-4990-11e9-9842-f47d5254b19c.png)
![plot log](https://user-images.githubusercontent.com/9381306/54560694-ee154380-4990-11e9-82a1-ea26678a74a1.png)

The command line being used is the following:
```
for kmer in {17,19,21,23,25}
do
  Rscript genoscope.R ${kmer}.hg ${kmer} 100 Genscope_${kmer}
done

```
I would like to test this tool in real data, but I am afraid that I won be using it if it cannot handle simple simulated data. Any help would be more than welcome.

BTW, KMC3 histogram requires replacement of "\t" for spaces in order to be compatible with current version of Genoscope.

Kind regards,

Juan D. Montenegro

**Comment by mschatz** [comment]
Hi Juan,

Could you send me your kmer histogram file? There might be other formatting issues at play since we typically use Jellyfish instead of KMC3

Cheers

Mike

**Comment by jdmontenegro** [comment]
Hi Mike,

Thanks for your quick reply. Please find attached the histogram for k=21. It was obtained with jellyfish as suggested for Genoscope. As I mentioned before I tried both KMC3 and Jellyfish and both failed to converge.
[sim.k21.hg.txt](https://github.com/schatzlab/genomescope/files/2981515/sim.k21.hg.txt)
Regards,
Juan D.

**Comment by mschatz** [comment]
Thanks for sending. Rhyker, could you try this with the new model using the
y*x or y*x^2 models? I think the high rate of heterozygosity is confusing
the GenomeScope 1.0 model

Thanks!

Mike

**Comment by tbenavi1** [comment]
Juan,


I have attached the results for your histogram file.


The new version of GenomeScope should be able to easily handle your data. This version should be available very soon for you to try.


T. Rhyker Ranallo-Benavidez

PhD Student | Biomedical Engineering | Johns Hopkins University

tbenavi1@jhu.edu | (509) 378-2783

________________________________

**Comment by tbenavi1** [comment]
Juan, I have attached the results for your histogram file. The new version of GenomeScope should be able to easily handle your data. This version should be available very soon for you to try. 
[sim.k21.hg_model.txt](https://github.com/schatzlab/genomescope/files/2997787/sim.k21.hg_model.txt)
![sim k21 hg_plot log](https://user-images.githubusercontent.com/20361021/54844407-3d1ee980-4cad-11e9-8350-f6efcba99d4e.png)
![sim k21 hg_plot](https://user-images.githubusercontent.com/20361021/54844416-43ad6100-4cad-11e9-9640-f9698983ee59.png)
[sim.k21.hg_progress.txt](https://github.com/schatzlab/genomescope/files/2997789/sim.k21.hg_progress.txt)
[sim.k21.hg_summary.txt](https://github.com/schatzlab/genomescope/files/2997790/sim.k21.hg_summary.txt)

**Comment by jdmontenegro** [comment]
Hi guys,
Thank you for your quick reply. I just have a question that may be silly. Is the model predicting the haploid genome size to be 6Mbp? Because I am expecting a 600 - 800 Mbp genome, based on flow cytometry and close relativesassemblies. Could you help me understand this better?
On another subject, is the model predicting between 11-13% of the genome to be heterozygous? and 0.41% to be repetitive? 
Thank you again for your help. I look forward to hearing back from you.

Kind regards,

Juan Daniel

**Comment by mschatz** [comment]
In your first email you said this was a simulated data set from "a small
plant diploid genome (genome size 13Mbp)". Does 13Mbp represent one or both
haplotypes? For example, the haploid genome size of human is 3Gbp, but the
total diploid genome size is 6Gb). The size that is reported here (6.5Mbp)
is the haploid genome size, and it infers a heterozygosity rate of 13.1%
and a very low rate of repetitive sequences (0.41%).

If you send the histogram for the real dataset (~600Mbp) we can help look
at that too.

Cheers

Mike

**Comment by jdmontenegro** [comment]
Dear Michael,

Apologies for the confusion. You are right, the test data was simulated
from a 13Mbp reference genome. I was expecting a homozygous genome since I
did not simulate heterozygosity. I will double check the reference genome
to see if it was in fact a phased assembly which would explain the results.

I look forward to using the new version on the actual 600Mbp genome I am
working on.

Kind regards,

Juan D. Montenegro

**Comment by mschatz** [comment]
If the data are supposed to be haploid, we can also use the ploidy=1 model
which will look for a single main peak for the unique kmers at ~45x, and
then the higher peak at ~90x will represent 2 copy repeats.

Good luck!

Mike
