### ISSUE TITLE
Bacterial reads

### ISSUE THREAD

**Issue by sarah872** [schatzlab/genomescope#23]
Hi there,
I am running genomescope for a set of bacterial reads, and I get meaningful results. But in what about heterozygosity? Since the organisms I am working with only have one copy of each gene (more or less), what does the value for heterozygosity mean with bacteria?

**Comment by mschatz** [comment]
For a clonal population, the heterozygosity should be very close to zero but there are a few causes for multiple peaks in the kmer graph. The main one is if there are variants within the population that you sequenced or even if there are multiple distinct strains present in the sample. Alternatively if there are high copy plasmids that can also lead to additional kmer peaks.

Good luck!

Mike

**Comment by sarah872** [comment]
Thanks!

**Comment by sarah872** [comment]
Thanks!
