### ISSUE TITLE
how to ensure k-mer value

### ISSUE THREAD

**Issue by George-du** [schatzlab/genomescope#25]
Hi,
   I want to assembly a small region of human chromosome Y, what should I do to choose a reasonable k-mer? You known that we often use 21-mer to assembly human genomics, but how I just want to de novo a small region of  human chromosome Y, do you think the  21-mer is ok?or I need to calculate new k-mer as formula：k = log4 (G(1−p)/p)（https://www.ncbi.nlm.nih.gov/pubmed/15087315?dopt=Abstract&holding=npg）
Thanks for your patient.
Best Duo

**Comment by mschatz** [comment]
If you have really isolated a small region you could probably use a smaller k value as you suggest. This is pretty straightforward for a simulation, but will be hard to do experimentally except if you were to isolate and amplify a bacterial artificial chromosome (BAC) or fosmid library.

Good luck

Mike

**Comment by George-du** [comment]
Hi, Mike
Thanks for your advises,I will attempt it.
Best,
Duo
