### ISSUE TITLE
longer kmers

### ISSUE THREAD

**Issue by roblanf** [schatzlab/genomescope#3]
as you point out in the docs, longer kmers are more prone to sequencing errors. But what do you think about ignoring unique kmers, since these are likely to be due to sequencing error. MASH does something like this through the -m command (mash.readthedocs.io) but I don't know if this would mess with your downstream calculations too much.

**Comment by roblanf** [comment]
From your ms (e.g. fig 1B), I see now that errors are a specific part of the model. In this case I'm less sure I understand the issue with longer k-mers. Does it somehow make the errors harder to model -it's not obvious to me how this works.

**Comment by fritzsedlazeck** [comment]
The issue is more on the other side. If the kmers are longer we are loosing more informative kmers due to the seq. error. E.g an error at every 50bp is fine, but an error every 20bp cause problems. We discussed that briefly in the revised manuscript. I hope we can share it soon.

**Comment by roblanf** [comment]
OK great - will close this since it doesn't seem sensible to leave it open if you have an answer that you'll share soon.
