### ISSUE TITLE
About Read length parameter for quality trimmed reads

### ISSUE THREAD

**Issue by EugeneKim76** [schatzlab/genomescope#31]
Deal all,
I am using genomescope with quality trimmed reads.
Is there any rules for selecting read length parameter for trimmed reads?
Should I have to use average read length or read length before trimmed?
Best,

**Comment by mschatz** [comment]
It turns out that this parameter is not actually used in the current
implementation so you can put in any value (100 is fine). We have actually
removed the parameter from the latest version:

http://genomescope.org/genomescope2.0
https://www.nature.com/articles/s41467-020-14998-3

Good luck!

Mike

**Comment by EugeneKim76** [comment]
Thank for kind answer.
Best,
