### ISSUE TITLE
Fail to converge

### ISSUE THREAD

**Issue by zy041225** [schatzlab/genomescope#34]
Hi,

This tool looks quite useful and I'm trying to use it to my own data. I run the Jellyfish with the following command to obtain reads.histo:

`zcat *.fq.gz | jellyfish count -C -m 21 -s 1G -t 10 /dev/fd/0 -o reads.jf`
`jellyfish histo -t 10 reads.jf > reads.histo`

After uploading the file, the plot looks nice but GenomeScope fail to converge. What should I do to get things work for this data? 

[reads.histo.txt](https://github.com/schatzlab/genomescope/files/4626293/reads.histo.txt)

Best,
Yang

**Comment by tbenavi1** [comment]
Yang,

Thanks for using this tool. We have updated GenomeScope to GenomeScope 2.0 which better converges on certain files. Please use GenomeScope 2.0 online at http://genomescope/genomescope2.0/ or download and run it on your own computer from https://github.com/tbenavi1/genomescope2.0. 

You can find the GenomeScope 2.0 results for your data at http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=8y0XQlNTN3Cx4sonIUTQ. Please let us know if you have any further questions.

**Comment by zy041225** [comment]
Thanks for your help and now GenomeScope2.0 works well to all my data.
