### ISSUE TITLE
Genomescope 2 vs. 1

### ISSUE THREAD

**Issue by jhcaddisfly** [schatzlab/genomescope#39]
Hello,

I observed the following:
I ran Genomescope 1 and 2 on the same Illumina reads and the results look like this:
Genomescope2: Ploidy 2 
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=G1hKSxiXYsf1G01H9GJC
Genomescope1:
http://qb.cshl.edu/genomescope/analysis.php?code=xzUtugQSH2tCADSJ3tMg

If I set ploidy to 1 in Genomescope 2 I get the following:
Genomescope2: Ploidy 1
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=0iaKscWqJTRuhvGxuBEE

Do you have any explanation for this?
Would you recommend using Genomescope 1 instead of Genomescope 2?
The assembly size fits the size obtained with Genomescope 1.

Thanks,
Jacqueline

**Comment by tbenavi1** [comment]
We recommend using Genomescope 2. You can use the "-l" parameter to set the location of the first peak. In your example, I would run Genomescope 2 with "-l 53".

**Comment by jhcaddisfly** [comment]
Perfect! Thanks a lot!
