### ISSUE TITLE
Webserver error

### ISSUE THREAD

**Issue by sarah872** [schatzlab/genomescope#45]
Hi,
I was trying to upload a histogram file (e.g. http://qb.cshl.edu/genomescope/genomescope2.0/tests/inputk21.hist), and it seems to upload, but after clicking SUBMIT, it throws the error "no file uploaded".

**Comment by mschatz** [comment]
Can you please try again? We had an issue on the server but should be
working now.

Thanks

Mike

**Comment by sarah872** [comment]
looks alright, thanks!

**Comment by bishopia** [comment]
Is this happening again by chance? I'm also receiving this "No file uploaded" error after what looks like a successful upload.

**Comment by mschatz** [comment]
Thanks for your interest - the server that hosts genomescope filled up the
local disk. I have purged it and everything should be working again. Good
luck!

Mike

**Comment by WJT0925** [comment]
Hi, I am also having the same issue.

**Comment by mschatz** [comment]
Please try again - I freed up some space this morning

Mike

**Comment by chancx** [comment]
Hello, I imagine the diskspace is filled up again? I've been getting "no file uploaded" error for the past hour. Thanks

**Comment by mschatz** [comment]
Yes, it filled but I was able to free up some space

Thanks!

Mike

**Comment by bioming** [comment]
I also got that problem now.

**Comment by chfal** [comment]
I also got the same error just now! Sorry to bother :)

**Comment by mschatz** [comment]
Apologies, we had a server issue but it should be resolved now. Thanks for
your interest!

Mike

**Comment by TannazDZ** [comment]
Hi,

I am having the same issue and I am not able to upload my *.hist (97KB) file. Could you please advise? 

Many thanks, Tannaz

**Comment by mschatz** [comment]
Please try again - the backend server filled up but I freed up some space.

Good luck!

Mike

**Comment by matin-miryeganeh** [comment]
Hi, Could you please try to free up some space again? I am having the same issue. many thanks!

**Comment by mschatz** [comment]
Please try again! I cleaned up a few hundred GB

Thanks!
Mike

**Comment by matin-miryeganeh** [comment]
Thank you!

**Comment by mschatz** [comment]
Cleaning up now!

**Comment by LapRag** [comment]
Hi, I have the same problem: No file uploaded.

Best
Lapo

**Comment by Surbhigrewal** [comment]
Please could you free up some space as we cannot upload files.
Thanks.

**Comment by Iredcg** [comment]
Hi, I am also having the same issue. 
Could you please free up some space.

Thank you!

**Comment by Haoran-Xue** [comment]
Hi, I am having the same issue. Can you please free up some space?

Thanks!

**Comment by lackna** [comment]
Hi, the server is not working likely because there is no space. Could you please help me?
Thank you

**Comment by SimonaSecomandi** [comment]
Hi, I have the same issue: No file uploaded. Thanks!

**Comment by lpereira89** [comment]
Hello! Same here.
Thanks!

**Comment by didier-aurelle** [comment]
Hi
I have the same problem now...
thanks!
Didier

**Comment by mschatz** [comment]
Please try again - the backend server filled up but I cleaned out some space

Good luck!

Mike

**Comment by didier-aurelle** [comment]
It works again! thanks!
Didier

**Comment by saidelhasnaoui** [comment]
I am having the same error in uploading .histo file. Could you please advise?
Many thanks,

**Comment by NickJeff13** [comment]
I am having the same issue as well on August 16th

**Comment by mschatz** [comment]
Please try again! The server filled up which prevented any one from
uploading, but I cleared out a few hundred GB of older results.

Thanks!
Mike

**Comment by calliphriend** [comment]
I am having the same error on September 8. Would greatly appreciate help! Thank you!

**Comment by blemmond** [comment]
Hi there, having the same issue here (Sept. 9 2023). Thank you!

**Comment by mschatz** [comment]
Please try again! I freed up 500GB on the server

Good luck!

Mike

**Comment by blemmond** [comment]
Ah, that did the trick! Thanks so much Mike!
Ben


Ben Lemmond
PhD Candidate, University of Florida
2523 Fifield Hall
2550 Hull Rd.
Gainesville, FL 32611

[cid:2ccbe434-7d98-4ca4-acfa-5f743f101689]
________________________________

**Comment by calliphriend** [comment]
Thank you very much! Much appreciated!

**Comment by marketavlkova** [comment]
Hi, I'm having the same issue (November 24, 2023).
Thank you

**Comment by Ain-Ali** [comment]
Hello Sir, again the server ran short on memory probably. The issue is "no file upload" . please respond it.

**Comment by mschatz** [comment]
Please try again - the server filled up but I cleaned out a lot of space

Good luck!

Mike
