### ISSUE TITLE
Is there a 'comprehensive' list of heterozygosity values in animals?

### ISSUE THREAD

**Issue by mickey-spongebob** [schatzlab/genomescope#56]
Heya :-) 

Thank you for the really nice tool! I managed to get the GenomeScope heterozygosity and genome size measurements. I'm struggling however to interpret my heterozygosity values, mostly because I'm not so knowledgeable on what are high vs. low heterozygosity percentages? For context, my results (from _Platynereis dumerilii_ which is a marine annelid) shows 3.19% heterozygosity, I used Illumina reads from a culture bred in laboratory conditions for many years :-)

I've had a look at the web server where there are a few examples, and it seems as though 3.19% is higher than bird, oyster and Drosophila. Is there any comprehensive list of animals sequenced and their estimated heterozygosity values? Naturally I've also looked at a few recently sequenced annelid genomes and they are also below 0.5%.

Sorry if this is not directly related to the tools itself. I was hopeful that maybe there is a list somewhere so that I can appreciate whether this is a high, modest or low number :-) 

Cheers and wishing you well! :-)

**Comment by mschatz** [comment]
Thanks for your interest. Unfortunately, Im not aware of any comprehensive
listing of heterozygosity values - The single biggest list I know of is
from the VGP with a list of about 20 species available in figure 3 here:
https://www.biorxiv.org/content/10.1101/2020.05.22.110833v1.full

But in my experience 3.19% is very high, probably the highest Ive seen from
an animal across perhaps 100 species or so. Was this taken from a single
animal or from a collection of animals? The only time Ive seen values this
high has been in F1 organisms in crosses between divergent strains of a
plant

Good luck

Mike

**Comment by mickey-spongebob** [comment]
Thank you for the reply :-)

The score was derived using GenomScope version 2, from Illumina reads that were trimmed, deduplicated and normalised. The sequencing was done on a single individual. The animals that we have were cultured in laboratory conditions since 1960s I believe. 

I could also sequence an 'inbred' strain where we in-crossed over several generations and measure heterozygosity and compare. There is also mollusc data showing equally high heterozygosity:
[https://academic.oup.com/gigascience/article/10/3/giab020/6187865](url)

They attributed this to minimal inbreeding. I'll continue searching and will compare the inbred strain also.

Thank you for your help and wishing you well :-)

Cheers
