### ISSUE TITLE
Wrong allocation of haplotype peak to error peak

### ISSUE THREAD

**Issue by zhoudreames** [schatzlab/genomescope#57]
![image](https://user-images.githubusercontent.com/54714639/116107362-8c824000-a6e5-11eb-878f-31520eeb3ac9.png)
in my Diploidy species Illumina data，I gain the kmer histogram by using k=31.but I find it wrong allocation of haplotype peak to error peak，how to solve the problem？

**Comment by tbenavi1** [comment]
If you are running from the command line (using version 2.0 found at https://github.com/tbenavi1/genomescope2.0) you can use the "-l" parameter to set the location of the first peak. For your data you would use "-l 48". On the website (genomescope.org/genomescope2.0/) you can set the average kmer coverage to 48. I hope that helps.
