### ISSUE TITLE
Genome size underestimate

### ISSUE THREAD

**Issue by YPGG1234** [schatzlab/genomescope#65]
Hi, @mschatz 

I ran Genomescope2 on male and female illumina data of one species (k=21), but I cannot explain the result which I got.

Male 
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=U2hepOoUB8LBphox9Rif

Female
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=9pGz223vXsz5SKkFmGNE

The genome size estimate is deviate from the expect genome size from previous studies on this species and on the closed species (Male genome ~2.1-2.4 Gb while female is little bit smaller than male, also ~2.1-2.4 Gb ) .

I increased both the high count value of Jellyfish and max k-mer coverage of Genomescope2 to 1,000,000，but it seems not work

Male
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=rzNJDK9AWtOIdz9mjilA

Female
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=4UsFcKwdawPB7tBaCnx7

Do you have any explanation?

Thank you!

**Comment by mschatz** [comment]
I dont see anything obviously wrong with the fit or the estimate. I will
say it is not uncommon for experimental techniques to measure genome size
to be off by 10% to 15% so I think these results are within the expected
range.

Good luck

Mike

**Comment by YPGG1234** [comment]
Thanks for your kindly reply!
