### ISSUE TITLE
Deviation of observed from full model 

### ISSUE THREAD

**Issue by chancx** [schatzlab/genomescope#68]
Hi, I ran GenomeScope2 at default setting, and the "observed" distribution appears to deviate quite substantially from the "full model". 
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=98nr9WHjGEaPmpTfZ4io
p = 2
k = 21 

I greatly appreciate any input/feedback on how should we interpret these results (e.g. if this indicate insufficient data, and on the determination of diploidy). Many thanks in advance.

**Comment by mschatz** [comment]
The low coverage of your data confused the automated fitting algorithm. By
setting "Average k-mer coverage for polyploid genome" to 5, it was able to
get a better fit:
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=KnIHuKJUYJ5vbIxzLgbp

But the very low coverage makes the estimates pretty unreliable. I would
strong recommend collecting additional data before attempting a de novo
assembly

Good luck!

Mike

**Comment by chancx** [comment]
Thanks, Mike. In this situation, is it reasonable to consider the haploid genome-size estimate at cov = 5 (with a better-fit model, 1.46Gbp) more reliable than that estimated at default (with a worse-fit model; 0.58 Gbp)? I imagine both estimates would be very rough given the limited amount of data. We do expect diploidy in this instance.

Cheers,
CX

**Comment by mschatz** [comment]
Yes the new fit is much better and should be much more reliable

Good luck

Mike

**Comment by chancx** [comment]
Thanks so much for your speedy responses! Cheers
