### ISSUE TITLE
Please add support from ntCard k-mer histograms

### ISSUE THREAD

**Issue by mmokrejs** [schatzlab/genomescope#8]
Hi,
  would you mind adding an auto-detection of data input to convert on the fly hist files from ntCard? See https://github.com/bcgsc/ntCard/issues/8#issuecomment-364635788

**Comment by mschatz** [comment]
We will consider this for the future but Im glad to see you have an easy workaround

Good luck

Mike

**Comment by mschatz** [comment]
Looking at ntCard more closely, it is a research question to evaluate if
the approximation scheme that ntCard uses produces robust results. Until
then it is not supported, especially since there are many other options
available.

Best,

Mike

**Comment by mohamadi** [comment]
Hi,

I just saw this thread related to ntCard and would like to mention that ntCard is a published wok/tool in Bioinformatics at https://doi.org/10.1093/bioinformatics/btw832

If you refer to the following figure in the paper, you'll see that ntCard results are near identical to the exact histogram generated by DSK:
https://academic.oup.com/view-large/figure/79927771/btw832f2.tif 

Regards,
Hamid
