### ISSUE TITLE
GenomeScope Error message

### ISSUE THREAD

**Issue by eli1199** [schatzlab/genomescope#81]
Hello, 

I ran jellyfish to count kmers in a genome that I assembled:

```
jellyfish count -m 21 -s 4200455 -t 8 assembly.fa -o counts.jf
jellyfish histo -t 8 counts.jf > counts.histo
```

However when I try to run counts.histo on the web version of genomescope I get the following error message:
<img width="532" alt="Screen Shot 2022-07-04 at 10 32 09 PM" src="https://user-images.githubusercontent.com/51135961/177240694-60d87c02-c6fa-4b3c-aef0-fee88983a30d.png">
:
Does anyone know why this happens Or how I can estimate heterozygosity from an assembly? alternatively I can try running jellyfish on the reads but I currently only have the raw reads not the filtered reads that were used to do the assembly.

Thank you.

**Comment by mschatz** [comment]
Thanks for your interest. GenomeScope is designed to run with kmer counts
directly from the sequencing reads, not the assembly itself. Depending on
your needs, you may also find Merqury useful to check the quality of an
assembly:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02134-9

Good luck!
Mike

**Comment by eli1199** [comment]
Thanks @mschatz  for the recommendation! Is there a way to run Genomescope if Im starting with a bam/sam file? Because then I can just map my raw reads to the assembly

**Comment by mschatz** [comment]
You can just just run jellyfish or another kmer counter) directly on the
raw reads in fastq format - no need to map the reads to the assembly. In
fact with GenomeScope you dont even need an assembly

Good luck!

Mike

**Comment by eli1199** [comment]
That's very helpful thank you! I will try both approaches and compare results.
