### ISSUE TITLE
Curious plant Kmer spectra from HiFi reads

### ISSUE THREAD

**Issue by NatJWalker-Hale** [schatzlab/genomescope#82]
Dear Mike and team, 

We are working with some PacBio HiFi data from a plant species. We sequenced libraries from the same individual in two batches, first two flow cells and then an additional three. The first two had relatively low yield (~20 Gb in total), and the Kmer spectra was unable to resolve peaks: http://genomescope.org/genomescope2.0/analysis.php?code=iv2XDyBMfAWMi3N5zY6k

Nonetheless, hifiasm with defaults was able to produce a primary assembly from just the first two flow cells of ~2Gb in length with ~75% complete BUSCOs.

After combining the additional three libraries (~110Gb in total) and counting 21mers, I get a spectra with a leftward shoulder, which I haven't seen before, and an extremely high heterozygous peak (not unexpected, wild collected seed): http://genomescope.org/genomescope2.0/analysis.php?code=0xl7my3kUygec4ZoLQk0

I used all the reads to produce an assembly with hifiasm, with the default kmer size of 51, which assembled a primary assembly of ~4 Gb and 98% complete BUSCOs, but with extremely high duplication rates, suggesting poor haplotype purging. Indeed, when I produce the GenomeScope spectra with 51mers, the shoulder resolves into a peak: http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=3HC49YnMrFo8q6FuZC2E

This appears to have caused hifiasm to call the homozygous peak wrong, hence the high duplication rate in BUSCOs.

So far, I can think of a few explanations:

1. Extremely high heterozygosity (not necessarily unexpected): how would it explain the shoulder in the Kmer spectra?
2. Accidental mix of individuals: this is almost certainly not the case, as I handled all the extractions myself from the same plant. Likewise, not sure how it might explain the results we see.
3. Error rates causing longer Kmers to have lower coverage, explaining the shoulder.

I would be very grateful to hear any thoughts you have on this, as I am a bit stumped.

Many thanks,

Nathanael

**Comment by mschatz** [comment]
Hi Nathanael

These plots are definitely weird - please see below


On Wed, Jul 13, 2022 at 8:25 AM Nathanael Walker-Hale <
***@***.***> wrote:

> Dear Mike and team,
>
> We are working with some PacBio HiFi data from a plant species. We
> sequenced libraries from the same individual in two batches, first two flow
> cells and then an additional three. The first two had relatively low yield
> (~20 Gb in total), and the Kmer spectra was unable to resolve peaks:
> http://genomescope.org/genomescope2.0/analysis.php?code=iv2XDyBMfAWMi3N5zY6k
>

I wouldnt trust any of the genomescope results here since as you say the
peaks are unresolved.

Nonetheless, hifiasm with defaults was able to produce a primary assembly
> from just the first two flow cells of ~2Gb in length with ~75% complete
> BUSCOs.
>
> After combining the additional three libraries (~110Gb in total) and
> counting 21mers, I get a spectra with a leftward shoulder, which I haven't
> seen before, and an extremely high heterozygous peak (not unexpected, wild
> collected seed):
> http://genomescope.org/genomescope2.0/analysis.php?code=0xl7my3kUygec4ZoLQk0
>

The leftward shoulder like this can come up from heterozygosity and/or
contamination. For example, you will see a plot like this if you mix data
from multiple heterozygous samples where most of the heterozygous kmers
have ~25x coverage but some of the heterozygous kmers have ~12x. But it
could also be that the model fit is getting confused about where is the
homozygous peak and where is the heterozygous peak. This is extremely high
heterozygosity and I bet it is confusing the repeats at 50x as the
homozygous peak (also see below)

I used all the reads to produce an assembly with hifiasm, with the default
> kmer size of 51, which assembled a primary assembly of ~4 Gb and 98%
> complete BUSCOs, but with extremely high duplication rates, suggesting poor
> haplotype purging. Indeed, when I produce the GenomeScope spectra with
> 51mers, the shoulder resolves into a peak:
> http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=3HC49YnMrFo8q6FuZC2E
>
This is pretty nuanced - notice the peaks here are centered at 12x and 25x
rather than 25x and 50x. So the shoulder hasnt really gone away, it is just
focusing on a different part of the kmer spectrum.

> This appears to have erroneously caused hifiasm to call the homozygous
> peak wrong, hence the high duplication rate in BUSCOs.
>
> So far, I can think of a few explanations:
>
>    1. Extremely high heterozygosity (not necessarily unexpected): how
>    would it explain the shoulder in the Kmer spectra?
>    2. Accidental mix of individuals: this is almost certainly not the
>    case, as I handled all the extractions myself from the same plant.
>    Likewise, not sure how it might explain the results we see.
>    3. Error rates causing longer Kmers to have lower coverage, explaining
>    the shoulder.
>
> I would be very grateful to hear any thoughts you have on this, as I am a
> bit stumped.
>

There is something definitely weird about these data. Have you tried an
analysis of just the last 3 flowcells? Are you sure this is diploid? I
sometimes see plots like this for tetraploids as well. Have you tried
smudgeplots?

Hope this helps

Mike



> Many thanks,
>
Nathanael

**Comment by NatJWalker-Hale** [comment]
Hi Mike, 

Thanks so much for your helpful reply, and apologies for my delayed response. We had no prior expectation that the plant was non-diploid, but no reason to rule it out either. I ran smudgeplot with a lower cutoff of 10 and an upper cutoff of 1600 (decided automatically by the script). The plots are below, and as you can see it suggests tetraploidy.

![smudgeplot_smudgeplot](https://user-images.githubusercontent.com/34058664/183057355-3cfa1589-1ed2-4113-a535-a76549ca155e.png)
![smudgeplot_smudgeplot_log10](https://user-images.githubusercontent.com/34058664/183057361-d966bc75-cff5-46ba-891f-d28c5dbb819f.png)

The canu primary assembly seemed to support this, being ~8.7 Gb in length with 98.8% complete buscos, of which ~94% were duplicated, and ~1100/1614 present in four or more copies. However, I was a bit leery of the smudgeplot because the smudge coverage seemed quite low, so I wanted to rule out whether it was something else, like maybe a mixture of two heterozygous individuals being confused as polyploid (although this seems intuitively plausible to me, I'm not sure that it actually is).

To do this, I mapped the reads from just our first round of sequencing, where the library was prepared from a single extraction which I know came from just 1 individual. I reasoned that if it was truly tetraploid, then there should be reads with primary alignments to each of the four haplophases represented in the primary assembly from all the reads. I did this by inspecting the mappings to contigs containing 4X duplicated BUSCOs and searching for unique reads with primary mappings to each contig containing one of the copies. For the examples that I checked, I found this pattern, which seems to support it truly being tetraploid (and perhaps allotetraploid? If I am interpreting the smudgeplots right).

The one major question I have remaining is how to get sensible genome size estimates in this case. Based on the apparent gene-space completeness of the assembly, I would expect the tetraploid size to be ~8.7 Gb (i.e., assuming the canu assembly is collapsing almost nothing). However, when I run genomescope with with ploidy set to 4, I get very large estimates.

21mer, p=4: http://genomescope.org/genomescope2.0/analysis.php?code=mgmvh1eHSzHaeSvGrC7Z
haploid size estimate of 861 Mb, 4n size 861 * 4 = 3.4 Gb

51mer, p=4: http://genomescope.org/genomescope2.0/analysis.php?code=2O1dMq9NFKc83dMIgc28
haploid size estimate of 897 Mb, 4n size 897 * 4 = 3.5 Gb

Perhaps I am misinterpreting the genomescope output, but it seems to me like the polyploid model is still struggling to identify the shoulder/early peak as a peak, and the size estimates are reflecting that. 

Would be grateful to hear any thoughts you have,

Many thanks again,

Nathanael

**Comment by mschatz** [comment]
Hi Nathan,

Please see below

On Fri, Aug 5, 2022 at 7:04 AM Nathanael Walker-Hale <
***@***.***> wrote:

> Hi Mike,
>
> Thanks so much for your helpful reply, and apologies for my delayed
> response. We had no prior expectation that the plant was non-diploid, but
> no reason to rule it out either. I ran smudgeplot with a lower cutoff of 10
> and an upper cutoff of 1600 (decided automatically by the script). The
> plots are below, and as you can see it suggests tetraploidy.
>
> [image: smudgeplot_smudgeplot]
> <https://user-images.githubusercontent.com/34058664/183057355-3cfa1589-1ed2-4113-a535-a76549ca155e.png>
> [image: smudgeplot_smudgeplot_log10]
> <https://user-images.githubusercontent.com/34058664/183057361-d966bc75-cff5-46ba-891f-d28c5dbb819f.png>
>
> The canu primary assembly seemed to support this, being ~8.7 Gb in length
> with 98.8% complete buscos, of which ~94% were duplicated, and ~1100/1614
> present in four or more copies. However, I was a bit leery of the
> smudgeplot because the smudge coverage seemed quite low, so I wanted to
> rule out whether it was something else, like maybe a mixture of two
> heterozygous individuals being confused as polyploid (although this seems
> intuitively plausible to me, I'm not sure that it actually is).
>
To do this, I mapped the reads from just our first round of sequencing,
> where the library was prepared from a single extraction which I know came
> from just 1 individual. I reasoned that if it was truly tetraploid, then
> there should be reads with primary alignments to each of the four
> haplophases represented in the primary assembly from all the reads. I did
> this by inspecting the mappings to contigs containing 4X duplicated BUSCOs
> and searching for unique reads with primary mappings to each contig
> containing one of the copies. For the examples that I checked, I found this
> pattern, which seems to support it truly being tetraploid (and perhaps
> allotetraploid? If I am interpreting the smudgeplots right).
>
Ah interesting. This is a nice way to confirm ploidy


> The one major question I have remaining is how to get sensible genome size
> estimates in this case. Based on the apparent gene-space completeness of
> the assembly, I would expect the tetraploid size to be ~8.7 Gb (i.e.,
> assuming the canu assembly is collapsing almost nothing). However, when I
> run genomescope with with ploidy set to 4, I get very large estimates.
>
> 21mer, p=4:
> http://genomescope.org/genomescope2.0/analysis.php?code=mgmvh1eHSzHaeSvGrC7Z
> haploid size estimate of 861 Mb, 4n size 861 * 4 = 3.4 Gb
>
> 51mer, p=4:
> http://genomescope.org/genomescope2.0/analysis.php?code=2O1dMq9NFKc83dMIgc28
> haploid size estimate of 897 Mb, 4n size 897 * 4 = 3.5 Gb
>
> Perhaps I am misinterpreting the genomescope output, but it seems to me
> like the polyploid model is still struggling to identify the shoulder/early
> peak as a peak, and the size estimates are reflecting that.
>
I agree, these are pretty poor fits so I would not trust the genome size
estimate. After some parameter tweaking I can get a little bit better fit
with a 4n genome size of 7.1Gb, although even this fit isnt great and is
missing some of the heterozygous kmers:
http://qb.cshl.edu/genomescope/genomescope2.0/analysis.php?code=aMvBLEO7en29sto7fs3y

My guess is the true genome size is someplace in between at around 8Gbp

Hope this helps

Mike

**Comment by NatJWalker-Hale** [comment]
Hi Mike,

Thanks so much for looking it over! Your adjusted fit seems like a much closer estimate. We will hopefully follow up with some cytometry for a confirmatory measure.

Thank you very much again for the help,

Nathanael
