### ISSUE TITLE
distinguishing recent WGD vs polypoidy in genomescope

### ISSUE THREAD

**Issue by mycowx** [schatzlab/genomescope#87]
I'm working on assembling a large mollusc genome and I'm having some trouble interpreting the genome scope results derived from a 150bp illumina library.  I suspect the genome is full of repetitive elements, but genome scope shows only ~10% unique.  I am wondering if this is a result of a recent WGD event or if this is possibly a ploidy issue.  I am also unsure if the peaks are called correctly, as there is an uncalled shoulder on the right of the kmer distribution that may correspond the fourth peak.  Any interpretations would be appreciated.

http://genomescope.org/genomescope2.0/analysis.php?code=zlf8P4pAGUdIfM31oxhe

**Comment by tbenavi1** [comment]
Based on the kmer spectra, I believe this organism is tetraploid. Can you
rerun genomescope with "-p 4" (ploidy 4 from the website) and then let us
know if you have any further interpretation issues? Thanks.

**Comment by mycowx** [comment]
Thank you for your quick response.  Here is the genomescope result for a tetraploid model:
http://genomescope.org/genomescope2.0/analysis.php?code=mTXSBGPfcjTWfd59aF2r

I have been running a smudgeplot over the weekend and hope to have results soon that can help with interpretation.  Smudgeplot is currently consuming 500GB of RAM while calculating kmer pairs!

Thanks again for your help.

**Comment by tbenavi1** [comment]
This model fit looks much better. From my experience, this organism is
definitely tetraploid. Each of the 4 homologs is a little over 1GB of
sequence. (For humans, each of the 2 homologs is around 3GB).

**Comment by mycowx** [comment]
Yes, this makes sense to me!  Thank you for providing this great piece of software and helping me understand the output!  I'll close the issue.  Cheers!
