### ISSUE TITLE
Reasons for model not converging

### ISSUE THREAD

**Issue by gbdias** [schatzlab/genomescope#9]
Hi,

I ran genomescope on a k-mer count histogram from 130x Illumina coverage and the model did not converge.
Since coverage here is not insufficient, can you think of other issues that could be preventing the model from converging?

Best,
Gui

**Comment by mschatz** [comment]
Can you email me the histo file? I can take a look to check

Mike

**Comment by gbdias** [comment]
Here is the file.

Thanks


On 28 Feb 2018, at 20:30, Michael Schatz <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you email me the histo file? I can take a look to check

Mike

**Comment by mschatz** [comment]
Moved to a private email exchange -- closing
