### ISSUE TITLE
No graph generated 

### ISSUE THREAD

**Issue by rosspdu** [schatzlab/genomescope#97]
Hello, 

I uploaded my 'reads.histo' file on http://qb.cshl.edu/genomescope/genomescope2.0/? and it showed a 'check' mark so I assumed it was uploaded successfully. However, when I clicked submit, it kept saying 'no file uploaded' for some reason. I was able to run this about a month ago without any problem so I'm not sure how to fix this. 

Thank you for your help. 

Ross

**Comment by mschatz** [comment]
Please try again - the backend server filled up but I cleaned out some space

Good luck!

Mike

**Comment by rosspdu** [comment]
Hello Mike,

Yes, it's working now! thank you

Ross
